### ISSUE TITLE
Size exceeded?

### ISSUE THREAD

**Issue by crozzy** [elewis787/hacket#3]
https://github.com/elewis787/hacket/blob/5e6125e279a1deb7800be40d9689300eea3cd92e/packet.go#L43

Is it possible that if you add a 65535 byte message with a message type that you will exceed the max bytes for a udp packet?

**Comment by elewis787** [comment]
Yes we could have 1 byte over. Planning on fixing by reserver 1 byte after the header. 

8 byte UDP Header  20 Byte IP Header, 1 byte Hacket header - rest available for packet contents.

fix in #4

**Comment by elewis787** [comment]
close
